version: '3.8'

services:
    db:
        image: 'postgres:latest'
        container_name: db
        environment:
            POSTGRES_DB: app
            POSTGRES_USER: umair
            POSTGRES_PASSWORD: umair
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        networks:
            - app-network

    app:
        image: 'iumairkhan/dummy-app:v1'
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        environment:
            POSTGRES_HOST: db
            POSTGRES_USER: umair
            POSTGRES_PASSWORD: umair
            POSTGRES_DB: app
        ports:
            - '3030:3030'
        depends_on:
            - db
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    db-data:
